updates:
  - package-ecosystem: "pub"
    commit-message:
      prefix: "Pub"
    directory: "/" 
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"
    versioning-strategy: auto
    
version: 2