name: photos
description: ente photos application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.q
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 0.8.55+575

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.1.0
  animate_do: ^2.0.0
  animated_list_plus: ^0.4.5
  archive: ^3.1.2
  background_fetch: ^1.2.1
  bip39: ^1.0.6
  cached_network_image: ^3.0.0
  chewie:
    git:
      url: https://github.com/ente-io/chewie.git
      ref: forked_video_player_plus
  clip_ggml:
    path: plugins/clip_ggml
  collection: # dart
  computer:
    git: "https://github.com/ente-io/computer.git"
  connectivity_plus:
    git:
      url: https://github.com/ente-io/plus_plugins.git
      ref: check_mobile_first
      path: packages/connectivity_plus/connectivity_plus/
  cross_file: ^0.3.3
  crypto: ^3.0.2
  cupertino_icons: ^1.0.0
  defer_pointer: ^0.0.2
  device_info_plus: ^9.0.3
  dio: ^4.0.6
  dots_indicator: ^2.0.0
  dotted_border: ^2.0.0+2
  dropdown_button2: ^2.0.0
  email_validator: ^2.0.1
  equatable: ^2.0.5
  event_bus: ^2.0.0
  exif: ^3.0.0
  expandable: ^5.0.1
  expansion_tile_card: ^3.0.0
  extended_image: ^8.1.1
  fade_indexed_stack: ^0.2.2
  fast_base58: ^0.2.1

  file_saver:
    # Use forked version till this PR is merged: https://github.com/incrediblezayed/file_saver/pull/87
    git: https://github.com/jesims/file_saver.git
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  fk_user_agent: ^2.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  flutter_cache_manager: ^3.3.0
  flutter_datetime_picker_bdaya: ^3.0.2
  flutter_displaymode: ^0.6.0
  flutter_easyloading: ^3.0.0
  flutter_email_sender: ^5.2.0
  flutter_image_compress: ^1.1.0
  flutter_inappwebview: ^5.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^12.0.4
  flutter_localizations:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_map_marker_cluster: ^1.2.0
  flutter_native_splash: ^2.2.0+1
  flutter_password_strength: ^0.1.6
  flutter_secure_storage: ^8.0.0
  flutter_sodium: ^0.2.0
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.0.6
  freezed_annotation: ^2.2.0
  google_nav_bar: ^5.0.5
  html_unescape: ^2.0.0
  http: ^1.1.0
  image: ^4.0.17
  image_editor: ^1.3.0
  in_app_purchase: ^3.0.7
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.0
  latlong2: ^0.9.0
  like_button: ^2.0.2
  loading_animations: ^2.1.0
  local_auth: ^2.1.5
  local_auth_android:
  local_auth_ios:
  logging: ^1.0.1
  lottie: ^1.2.2
  media_extension: ^1.0.1
  ml_linalg: ^13.11.31
  media_kit: ^1.1.10+1
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4
  modal_bottom_sheet: ^3.0.0-pre
  motion_photos:
    git: "https://github.com/ente-io/motion_photo.git"
  motionphoto:
    git: "https://github.com/ente-io/motionphoto.git"
  move_to_background: ^1.0.2

  # open_file: ^3.2.1
  onnxruntime:
    git: "https://github.com/ente-io/onnxruntime.git"
  open_mail_app: ^0.4.5
  package_info_plus: ^4.1.0
  page_transition: ^2.0.2
  password_strength: ^0.2.0
  path: #dart
  path_provider: ^2.1.1
  pedantic: ^1.9.2
  photo_manager: ^2.5.0
  photo_view: ^0.14.0
  pinput: ^1.2.2
  pointycastle: ^3.7.3
  provider: ^6.0.0
  quiver: ^3.0.1
  receive_sharing_intent: ^1.4.5
  scrollable_positioned_list: ^0.3.5
  sentry: ^7.9.0
  sentry_flutter: ^7.9.0
  share_plus: ^4.0.10
  shared_preferences: ^2.0.5
  simple_cluster: ^0.3.0
  sqflite: ^2.3.0
  sqflite_migration: ^0.3.0
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.19+1
  step_progress_indicator: ^1.0.2
  styled_text: ^7.0.0
  syncfusion_flutter_core: ^19.2.49
  syncfusion_flutter_sliders: ^19.2.49
  synchronized: ^3.1.0
  tflite_flutter: ^0.10.1
  #  tflite_flutter_helper:
  #    git:
  #      url: https://github.com/pnyompen/tflite_flutter_helper.git  # Fixes https://github.com/am15h/tflite_flutter_helper/issues/57
  tuple: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.3
  uuid: ^3.0.7
  video_player:
    git:
      url: https://github.com/ente-io/packages.git
      ref: android_video_roation_fix
      path: packages/video_player/video_player/
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.3.3
  wakelock_plus: ^1.1.1
  wallpaper_manager_flutter: ^0.0.2
  wechat_assets_picker: ^8.6.3
  widgets_to_image: ^0.0.2
  flutter_isolate: ^2.0.4
  protobuf: ^3.1.0
  pool: ^1.5.1
  

dependency_overrides:
  # current fork of tfite_flutter_helper depends on ffi: ^1.x.x
  # but we need ffi: ^2.0.1 for newer packages. The original tfite_flutter_helper
  #
  ffi: ^2.0.1
  video_player:
    git:
      url: https://github.com/ente-io/packages.git
      ref: android_video_roation_fix
      path: packages/video_player/video_player/
  watcher: ^1.1.0

flutter_intl:
  enabled: true

dev_dependencies:
  build_runner: ^2.4.7
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  integration_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  json_serializable: ^6.6.1
  test: ^1.22.0

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_foreground: "assets/launcher_icon/ente-icon-foreground.png"
  adaptive_icon_background: "#ffffff"
  ios: true
  image_path: "assets/icon-light.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/splash-screen-light.png
  image_dark: assets/splash-screen-dark.png
  android_fullscreen: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/splash-screen-light.png
    image_dark: assets/splash-screen-dark.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/models/blazeface/
    - assets/models/cocossd/
    - assets/models/mobilefacenet/
    - assets/models/mobilenet/
    - assets/models/scenes/
    - assets/models/yolov5face/
    - assets/models/clip/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Flutter localization
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
