name: photos
description: ente photos application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.44+324

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  adaptive_theme: ^2.3.0
  alice:
    git: "https://github.com/jhomlala/alice.git"
  animate_do: ^2.0.0
  archive: ^3.1.2
  background_fetch: ^1.0.1
  bip39: ^1.0.6
  cached_network_image: ^3.0.0
  chewie:
    path: thirdparty/chewie
  computer: ^2.0.0
  confetti: ^0.6.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.0
  device_info: ^2.0.2
  dio: ^4.0.0
  dots_indicator: ^2.0.0
  dotted_border: ^2.0.0+2
  email_validator: ^2.0.1
  event_bus: ^2.0.0
  exif: ^3.0.0
  expandable: ^5.0.1
  expansion_tile_card: ^2.0.0
  extended_image: ^6.2.1
  fast_base58: ^0.2.1
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_datetime_picker: ^1.5.1
  flutter_easyloading: ^3.0.0
  flutter_email_sender: ^5.1.0
  flutter_image_compress: ^1.1.0
  flutter_inappwebview: ^5.3.2
  flutter_launcher_icons: ^0.9.3
  flutter_local_notifications: ^9.5.3+1
  flutter_native_splash: ^2.2.0+1
  flutter_password_strength: ^0.1.6
  password_strength: ^0.2.0
  flutter_secure_storage: ^4.2.0
  flutter_sodium: ^0.2.0
  flutter_typeahead: ^4.0.0
  fk_user_agent: ^2.0.1
  flutter_windowmanager: ^0.2.0
  fluttercontactpicker: ^4.7.0
  fluttertoast: ^8.0.6
  google_nav_bar: ^5.0.5
  http: ^0.13.4
  image: ^3.0.2
  image_editor: ^1.0.0
  implicitly_animated_reorderable_list: ^0.4.0
  in_app_purchase: ^0.5.2
  intl: ^0.17.0
  like_button: ^2.0.2
  loading_animations: ^2.1.0
  local_auth: ^1.1.5
  logging: ^1.0.1
  lottie: ^1.2.2
  motionphoto:
    git: "https://github.com/ente-io/motionphoto.git"
  move_to_background: ^1.0.2
  open_file: ^3.2.1
  package_info_plus: ^1.0.1
  page_transition: ^2.0.2
  path_provider: ^2.0.1
  pedantic: ^1.9.2
  photo_manager: ^2.0.8
  photo_view: ^0.14.0
  pinput: ^1.2.2
  provider: ^6.0.0
  quiver: ^3.0.1
  receive_sharing_intent: ^1.4.5
  scrollable_positioned_list: ^0.2.2
  sentry:
    path: thirdparty/sentry-dart/dart
  sentry_flutter:
    path: thirdparty/sentry-dart/flutter
  share_plus: ^4.0.4
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  sqflite_migration: ^0.3.0
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_core: ^19.2.49
  syncfusion_flutter_sliders: ^19.2.49
  tuple: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.3
  uuid: ^3.0.4
  video_player:
    path: thirdparty/plugins/packages/video_player/video_player
  video_thumbnail: ^0.4.3
  visibility_detector: ^0.2.2
  wallpaper_manager_flutter: ^0.0.2

dependency_overrides:
  provider: ^6.0.1 # for chewie 1.2.2 https://github.com/brianegan/chewie/issues/530

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter_icons:
  android: true
  image_path_android: "assets/icon-light-curved.png"
  ios: true
  image_path_ios: "assets/icon-light.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/splash-screen-light.png
  image_dark: assets/splash-screen-dark.png
  android_fullscreen: true
  android_gravity: center
  ios_content_mode: center

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
  fonts:
  - family: Inter
    fonts:
      - asset: fonts/Inter-Regular.ttf
      - asset: fonts/Inter-Medium.ttf
      - asset: fonts/Inter-Light.ttf
      - asset: fonts/Inter-SemiBold.ttf
      - asset: fonts/Inter-Bold.ttf
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Bold.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Flutter localization
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
